### ISSUE TITLE
Iron Chests inventory crash

### ISSUE THREAD

**Issue by Ashley123477** [magmafoundation/Magma-1.16-Issues#22]
Iron Chests work and now show an inventory but placing any item inside instantly crashes the server

[crash-2020-10-27_07.04.43-server.txt](https://github.com/magmafoundation/Magma-1.16-Issues/files/5446059/crash-2020-10-27_07.04.43-server.txt)

**Comment by joaoespanhol** [comment]
this resolved with the new magma version
