### ISSUE TITLE
[Minecraft] Breaking a chest throws error and no chest item

### ISSUE THREAD

**Issue by remplerus** [magmafoundation/Magma-1.16-Issues#9]
What is wrong: Breaking a chest throws an error and the chest item isn't dropped. Also no access either on the chest without errors, it's just not working.
Just the Error (99% of my logs are in my other posts): https://mclo.gs/jFjVx0m
Magma Version: 34.1.19-3549466
Mods List: None
Plugin List: None
Server OS: Linux 8GB (ElixirNode Server) + Windows 10 6GB allocated RAM
Client OS: Windows 10 12GB allocated RAM Forge 34.1.19 without any mods

**Comment by Hexeption** [comment]
Can't replicate
